// Shared utilities so individual specs stay focused on their scenario.

/**
 * Sets the Vercel Deployment Protection bypass header on the page so that
 * Playwright's headless browser is not blocked by the security checkpoint.
 *
 * Reads the secret from the VERCEL_AUTOMATION_BYPASS_SECRET environment
 * variable. If the variable is not set the function is a no-op, which keeps
 * local development working without any extra configuration.
 *
 * To enable this on CI / Vercel preview deployments:
 *   1. In your Vercel project settings enable "Deployment Protection".
 *   2. Copy the generated bypass secret.
 *   3. Add it as a CI secret named VERCEL_AUTOMATION_BYPASS_SECRET.
 *   4. Pass it to Playwright via the env block in your workflow / playwright.config.
 */
export async function setBypassHeader(page) {
  const secret = process.env.VERCEL_AUTOMATION_BYPASS_SECRET;
  if (secret) {
    await page.context().setExtraHTTPHeaders({
      'x-vercel-protection-bypass': secret,
      'x-vercel-set-bypass-cookie': 'samesitenone',
    });
  }
}

export const SAMPLE_QUIZ = {
  id: 'quiz-test-1',
  title: 'Capitals',
  questions: [
    {
      id: 'q-1',
      text: 'Capital of France?',
      options: ['Paris', 'Berlin', 'Madrid', 'Rome'],
      correctIndex: 0,
      timeLimit: 30,
    },
  ],
  createdAt: 0,
  updatedAt: 0,
};

// Pre-seeds a quiz directly into localStorage so multiplayer tests don't
// have to re-traverse the creator UI.
export async function seedQuiz(page, quiz = SAMPLE_QUIZ) {
  await setBypassHeader(page);
  await page.goto('/');
  await page.evaluate((q) => {
    localStorage.setItem('kahootlite:quizzes', JSON.stringify([q]));
  }, quiz);
}

// Drives a host page from quiz library to the live lobby and returns the PIN.
export async function hostSeededQuiz(page) {
  await setBypassHeader(page);
  await page.goto('/#/quizzes');
  // Wait for the React app to fully hydrate before interacting with the quiz library.
  await page.waitForLoadState('networkidle');
  // Also wait explicitly for the Host → button to be visible — networkidle alone
  // may not be sufficient on cold Vercel deployments where React hydration lags.
  const hostBtn = page.getByRole('button', { name: /Host →/ });
  await hostBtn.waitFor({ state: 'visible', timeout: 15_000 });
  await hostBtn.click();
  await page.waitForURL(/#\/host\//);
  const code = (await page.locator('.big-code').first().innerText()).trim();
  return code;
}

export async function joinAs(page, code, name) {
  await page.goto(`/#/join/${code}`);
  await page.getByLabel('Your nickname').fill(name);
  await page.getByRole('button', { name: /Join game/ }).click();
}
